# Generated by Django 6.0.4 on 2026-04-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_cloudreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudreport',
            name='file_size',
            field=models.FloatField(default=0),
        ),
    ]
