# Generated by Django 6.0.4 on 2026-04-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_cloudreport_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudreport',
            name='public_id',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
